# Generated by Django 4.1 on 2024-05-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhanVien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvienquanly',
            name='luong_hang_thang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nhanviensanxuat',
            name='luong_hang_thang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nhanvienvanphong',
            name='luong_hang_thang',
            field=models.IntegerField(default=0),
        ),
    ]
