# Generated by Django 4.1 on 2024-05-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhanVien', '0003_bangnhanvien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangnhanvien',
            name='nhan_vien',
        ),
        migrations.AddField(
            model_name='bangnhanvien',
            name='ho_ten',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bangnhanvien',
            name='luong_hang_thang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bangnhanvien',
            name='ma_nv',
            field=models.IntegerField(default=0),
        ),
    ]
